// Draws the board's pen marks (the underline beneath the headline's count, the
// loop around an outage) and writes them to src/components/status/pen-marks.ts
// as constants:
//
//   node scripts/pen-paths.mjs          rewrite the file
//   node scripts/pen-paths.mjs --check  exit 1 when the file is out of date
//
// The marks are constants on purpose. A path computed at render time from
// Math.sin would be summed by the server's engine and again by the browser's,
// and one digit of difference is a hydration mismatch. Here the sums run once,
// on one machine, and the result is text.
//
// A mark is a variable-width filled outline through a dense, slightly wobbling
// centre line: thin at both ends where the pen lands and lifts, fullest a
// little past the start. The wobble is a seeded random, so a seed is a hand.

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath, pathToFileURL } from "node:url";

/** A small seeded random (mulberry32): the same seed always writes the same hand. */
export function rng(seed) {
  let a = seed >>> 0;
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const round = (n) => +n.toFixed(1);

/**
 * A pen stroke: the filled outline of a variable-width line through `pts`.
 * `base` is the widest half-width; `taper` the fraction of the length that
 * tapers at each end; `min` the width at the very tip as a fraction of `base`;
 * `swell` a slow pressure wobble along the stroke.
 */
export function pen(pts, base, taper = 0.14, min = 0.35, swell = 0) {
  const n = pts.length;
  const left = [];
  const right = [];
  for (let i = 0; i < n; i++) {
    const a = pts[Math.max(0, i - 1)];
    const b = pts[Math.min(n - 1, i + 1)];
    let dx = b[0] - a[0];
    let dy = b[1] - a[1];
    const d = Math.hypot(dx, dy) || 1;
    dx /= d;
    dy /= d;
    const t = i / (n - 1);
    const e = Math.min(t, 1 - t) / taper;
    const w =
      base * (min + (1 - min) * Math.min(1, Math.sin((Math.min(1, e) * Math.PI) / 2))) * (1 + swell * Math.sin(t * 9));
    left.push([pts[i][0] - dy * w, pts[i][1] + dx * w]);
    right.push([pts[i][0] + dy * w, pts[i][1] - dx * w]);
  }
  const outline = left.concat(right.reverse());
  return `M${outline.map((p) => `${round(p[0])} ${round(p[1])}`).join("L")}z`;
}

/** A slightly imperfect loop around (cx, cy): starts high on the left and overshoots its own start. */
export function loop(cx, cy, r, seed, turns = 1.07, steps = 96) {
  const rnd = rng(seed);
  const p1 = rnd() * 6;
  const p2 = rnd() * 6;
  const p3 = rnd() * 6;
  const pts = [];
  const a0 = -Math.PI * (0.62 + rnd() * 0.1);
  for (let i = 0; i < steps; i++) {
    const t = i / (steps - 1);
    const a = a0 + t * turns * 2 * Math.PI;
    const rad =
      r * (1 + 0.035 * Math.sin(2 * a + p1) + 0.02 * Math.sin(3 * a + p2) + 0.04 * (t - 0.5)) + r * 0.07 * t * t;
    // A hand-drawn ellipse: a touch wider than tall.
    pts.push([cx + Math.cos(a) * rad * 1.06 + 1.5 * Math.sin(a * 1.5 + p3), cy + Math.sin(a) * rad * 0.96]);
  }
  return pts;
}

/** A confident underline with a little drift. */
export function underline(x0, x1, y, seed, steps = 64) {
  const rnd = rng(seed);
  const p = rnd() * 6;
  const pts = [];
  for (let i = 0; i < steps; i++) {
    const t = i / (steps - 1);
    pts.push([x0 + (x1 - x0) * t, y - ((2.2 * (x1 - x0)) / 240) * t + 1.1 * Math.sin(t * 5 + p) + 2.5 * t * t]);
  }
  return pts;
}

/** The underline's box, in the units of its path. It is stretched to the width of the word. */
export const UNDERLINE_BOX = { width: 240, height: 12 };
/** The loop's box: a 22px glyph centred at (11, 11), with 8 units of room round it. */
export const LOOP_BOX = { min: -8, size: 38, glyph: 22 };
/** Three hands, so two outages side by side are not the same stroke twice. */
export const LOOP_SEEDS = [7, 3, 11];

export function marks() {
  const { width, height } = UNDERLINE_BOX;
  const c = LOOP_BOX.glyph / 2;
  return {
    underline: pen(underline(2, width - 3, height - 5, 4), 1.35, 0.2, 0.3, 0.1),
    loops: LOOP_SEEDS.map((seed) => pen(loop(c, c, LOOP_BOX.glyph * 0.68, seed, 1.07), 0.85, 0.16, 0.3, 0.1)),
  };
}

/** The exact text of src/components/status/pen-marks.ts. */
export function render() {
  const { underline: ul, loops } = marks();
  const box = `${LOOP_BOX.min} ${LOOP_BOX.min} ${LOOP_BOX.size} ${LOOP_BOX.size}`;
  const lines = [
    "// Generated by scripts/pen-paths.mjs (node scripts/pen-paths.mjs). Do not edit by hand.",
    "//",
    "// Constants, not computed: a path summed at render time could differ by a digit between the",
    "// server and the browser, and that is a hydration mismatch.",
    "",
    "/** The underline's viewBox; the path is stretched to the width of the word it sits under. */",
    `export const UNDERLINE_VIEW_BOX = "0 0 ${UNDERLINE_BOX.width} ${UNDERLINE_BOX.height}";`,
    "",
    "export const UNDERLINE_PATH =",
    `  "${ul}";`,
    "",
    "/** The loop's viewBox: a 22px glyph at (11, 11) with 8 units of room round it, drawn at 38px. */",
    `export const LOOP_VIEW_BOX = "${box}";`,
    "",
    "/** Three hands; the loop takes one by seed. */",
    "export const LOOP_PATHS = [",
    ...loops.map((d) => `  "${d}",`),
    "] as const;",
    "",
  ];
  return lines.join("\n");
}

const target = fileURLToPath(new URL("../src/components/status/pen-marks.ts", import.meta.url));

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const text = render();
  if (process.argv.includes("--check")) {
    let current = "";
    try {
      current = readFileSync(target, "utf8");
    } catch {
      // Missing counts as out of date.
    }
    // Compare without whitespace: the committed file is run through the formatter.
    if (current.replace(/\s+/g, "") !== text.replace(/\s+/g, "")) {
      console.error("src/components/status/pen-marks.ts is out of date: run node scripts/pen-paths.mjs");
      process.exit(1);
    }
  } else {
    writeFileSync(target, text);
    console.log(`wrote ${target}`);
  }
}
