/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FeedDotxmlRouteImport } from './routes/feed[.]xml'
import { Route as HealthzRouteImport } from './routes/healthz'
import { Route as MetricsRouteImport } from './routes/metrics'
import { Route as ReadyzRouteImport } from './routes/readyz'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ApiHistoryDotjsonRouteImport } from './routes/api/history[.]json'
import { Route as ApiStatusDotjsonRouteImport } from './routes/api/status[.]json'
import { Route as ApiBadgeServiceRouteImport } from './routes/api/badge/$service'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedDotxmlRoute = FeedDotxmlRouteImport.update({
  id: '/feed.xml',
  path: '/feed.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthzRoute = HealthzRouteImport.update({
  id: '/healthz',
  path: '/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsRoute = MetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadyzRoute = ReadyzRouteImport.update({
  id: '/readyz',
  path: '/readyz',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistoryDotjsonRoute = ApiHistoryDotjsonRouteImport.update({
  id: '/api/history.json',
  path: '/api/history.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatusDotjsonRoute = ApiStatusDotjsonRouteImport.update({
  id: '/api/status.json',
  path: '/api/status.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBadgeServiceRoute = ApiBadgeServiceRouteImport.update({
  id: '/api/badge/$service',
  path: '/api/badge/$service',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/healthz': typeof HealthzRoute
  '/metrics': typeof MetricsRoute
  '/readyz': typeof ReadyzRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/api/history.json': typeof ApiHistoryDotjsonRoute
  '/api/status.json': typeof ApiStatusDotjsonRoute
  '/api/badge/$service': typeof ApiBadgeServiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/healthz': typeof HealthzRoute
  '/metrics': typeof MetricsRoute
  '/readyz': typeof ReadyzRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/api/history.json': typeof ApiHistoryDotjsonRoute
  '/api/status.json': typeof ApiStatusDotjsonRoute
  '/api/badge/$service': typeof ApiBadgeServiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/healthz': typeof HealthzRoute
  '/metrics': typeof MetricsRoute
  '/readyz': typeof ReadyzRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/api/history.json': typeof ApiHistoryDotjsonRoute
  '/api/status.json': typeof ApiStatusDotjsonRoute
  '/api/badge/$service': typeof ApiBadgeServiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/feed.xml'
    | '/healthz'
    | '/metrics'
    | '/readyz'
    | '/robots.txt'
    | '/api/history.json'
    | '/api/status.json'
    | '/api/badge/$service'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/feed.xml'
    | '/healthz'
    | '/metrics'
    | '/readyz'
    | '/robots.txt'
    | '/api/history.json'
    | '/api/status.json'
    | '/api/badge/$service'
  id:
    | '__root__'
    | '/'
    | '/feed.xml'
    | '/healthz'
    | '/metrics'
    | '/readyz'
    | '/robots.txt'
    | '/api/history.json'
    | '/api/status.json'
    | '/api/badge/$service'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FeedDotxmlRoute: typeof FeedDotxmlRoute
  HealthzRoute: typeof HealthzRoute
  MetricsRoute: typeof MetricsRoute
  ReadyzRoute: typeof ReadyzRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  ApiHistoryDotjsonRoute: typeof ApiHistoryDotjsonRoute
  ApiStatusDotjsonRoute: typeof ApiStatusDotjsonRoute
  ApiBadgeServiceRoute: typeof ApiBadgeServiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed.xml': {
      id: '/feed.xml'
      path: '/feed.xml'
      fullPath: '/feed.xml'
      preLoaderRoute: typeof FeedDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthz': {
      id: '/healthz'
      path: '/healthz'
      fullPath: '/healthz'
      preLoaderRoute: typeof HealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics': {
      id: '/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readyz': {
      id: '/readyz'
      path: '/readyz'
      fullPath: '/readyz'
      preLoaderRoute: typeof ReadyzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history.json': {
      id: '/api/history.json'
      path: '/api/history.json'
      fullPath: '/api/history.json'
      preLoaderRoute: typeof ApiHistoryDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/status.json': {
      id: '/api/status.json'
      path: '/api/status.json'
      fullPath: '/api/status.json'
      preLoaderRoute: typeof ApiStatusDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/badge/$service': {
      id: '/api/badge/$service'
      path: '/api/badge/$service'
      fullPath: '/api/badge/$service'
      preLoaderRoute: typeof ApiBadgeServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FeedDotxmlRoute: FeedDotxmlRoute,
  HealthzRoute: HealthzRoute,
  MetricsRoute: MetricsRoute,
  ReadyzRoute: ReadyzRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  ApiHistoryDotjsonRoute: ApiHistoryDotjsonRoute,
  ApiStatusDotjsonRoute: ApiStatusDotjsonRoute,
  ApiBadgeServiceRoute: ApiBadgeServiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
